export * from "@/lib/db/schema/auth";
export * from "@/lib/db/schema/account";
export * from "@/lib/db/schema/chat";
export * from "@/lib/db/schema/projects";
export * from "@/lib/db/schema/source-material";
export * from "@/lib/db/schema/entities";
export * from "@/lib/db/schema/outlines";
export * from "@/lib/db/schema/scenes";
export * from "@/lib/db/schema/generation";
export * as legacySchema from "@/lib/db/schema/legacy";
