"use server";

import { generateObject, generateText } from "ai";
import { z } from "zod";
import { getSelectedModelId } from "@/lib/ai/models";
import { myProvider } from "@/lib/ai/providers";
import type { JulesPlan } from "@/lib/jules-client";
import type { Result } from "@/lib/result";

// --- Actions ---

export async function enhanceJulesPromptAction(
	draft: string,
): Promise<Result<string>> {
	try {
		if (!draft || draft.length < 5) {
			return { success: false, error: "Prompt is too short to enhance." };
		}

		const modelId = await getSelectedModelId("middle"); // Use 'middle' for good balance

		const { text } = await generateText({
			model: myProvider.languageModel(modelId),
			system: `You are an expert technical lead. Your goal is to refine user tasks into precise, actionable instructions for an autonomous AI developer agent.
			Ensure the prompt covers:
			1. Specific goals
			2. Edge cases
			3. Testing requirements
			4. Context/Constraints

			Output ONLY the refined prompt text. Do not add conversational filler.`,
			prompt: `Refine this task: "${draft}"`,
		});

		return { success: true, data: text };
	} catch (error) {
		console.error("Failed to enhance prompt:", error);
		const message = error instanceof Error ? error.message : String(error);
		return { success: false, error: `Enhancement failed: ${message}` };
	}
}

export async function reviewJulesPlanAction(
	plan: JulesPlan,
): Promise<
	Result<{ riskLevel: string; analysis: string; recommendations: string[] }>
> {
	try {
		const modelId = await getSelectedModelId("large"); // Use 'large' for reasoning

		const { object } = await generateObject({
			model: myProvider.languageModel(modelId),
			schema: z.object({
				riskLevel: z.enum(["LOW", "MEDIUM", "HIGH", "CRITICAL"]),
				analysis: z.string(),
				recommendations: z.array(z.string()),
			}),
			system: `You are a Senior Staff Engineer reviewing a plan generated by an AI agent.
			Analyze the steps for safety, logic gaps, and potential side effects.
			Be critical but constructive.`,
			prompt: `Review this plan:\n${JSON.stringify(plan.steps, null, 2)}`,
		});

		return { success: true, data: object };
	} catch (error) {
		console.error("Failed to review plan:", error);
		const message = error instanceof Error ? error.message : String(error);
		return { success: false, error: `Review failed: ${message}` };
	}
}

export async function generateSessionTitleAction(
	prompt: string,
): Promise<string> {
	try {
		const modelId = await getSelectedModelId("light");
		const { text } = await generateText({
			model: myProvider.languageModel(modelId),
			system:
				"Generate a concise title (3-6 words) for this task. Output ONLY the title.",
			prompt: prompt,
		});
		return text.replace(/^["']|["']$/g, "").trim();
	} catch {
		return "Untitled Session";
	}
}
