"use server";

import { generateObject, generateText } from "ai";
import fs from "fs/promises";
import path from "path";
import { z } from "zod";
import { createAdminAction } from "@/lib/action-middleware";
import { getSelectedModelId } from "@/lib/ai/models";
import { myProvider } from "@/lib/ai/providers";

// ============================================================================
// Validation Schemas
// ============================================================================

const enhancePromptSchema = z.object({
	draft: z.string().min(5, "Prompt is too short to enhance"),
});

const reviewPlanSchema = z.object({
	plan: z.object({
		steps: z.array(
			z.object({
				description: z.string(),
				state: z.string().optional(),
			}),
		),
	}),
});

const discoverFeaturesSchema = z.object({});

const planFeatureSchema = z.object({
	title: z.string(),
	description: z.string().optional(),
});

// ============================================================================
// Helpers
// ============================================================================

async function getProjectContext() {
	try {
		const rootDir = process.cwd();
		const [agentsMd, archMd] = await Promise.all([
			fs.readFile(path.join(rootDir, "AGENTS.md"), "utf-8").catch(() => ""),
			fs
				.readFile(path.join(rootDir, "docs/architecture-overview.md"), "utf-8")
				.catch(() => ""),
		]);
		return `
=== PROJECT STANDARDS (AGENTS.md) ===
${agentsMd}

=== ARCHITECTURE (architecture-overview.md) ===
${archMd}
`;
	} catch (error) {
		console.error("Failed to read context files:", error);
		return "";
	}
}

// ============================================================================
// Actions
// ============================================================================

/**
 * Enhance a user's draft prompt into a more detailed, actionable instruction
 */
export const enhanceJulesPromptAction = createAdminAction({
	input: enhancePromptSchema,
	handler: async ({ input }) => {
		const modelId = await getSelectedModelId("middle");

		const { text } = await generateText({
			model: myProvider.languageModel(modelId),
			system: `You are an expert technical lead. Your goal is to refine user tasks into precise, actionable instructions for an autonomous AI developer agent.
			Ensure the prompt covers:
			1. Specific goals
			2. Edge cases
			3. Testing requirements
			4. Context/Constraints

			Output ONLY the refined prompt text. Do not add conversational filler.`,
			prompt: `Refine this task: "${input.draft}"`,
		});

		return text;
	},
});

/**
 * Review a Jules plan using AI for security and logic analysis
 */
export const reviewJulesPlanAction = createAdminAction({
	input: reviewPlanSchema,
	handler: async ({ input }) => {
		const modelId = await getSelectedModelId("large");

		const { object } = await generateObject({
			model: myProvider.languageModel(modelId),
			schema: z.object({
				riskLevel: z.enum(["LOW", "MEDIUM", "HIGH", "CRITICAL"]),
				analysis: z.string(),
				recommendations: z.array(z.string()),
			}),
			system: `You are a Senior Staff Engineer reviewing a plan generated by an AI agent.
			Analyze the steps for safety, logic gaps, and potential side effects.
			Be critical but constructive.`,
			prompt: `Review this plan:\n${JSON.stringify(input.plan.steps, null, 2)}`,
		});

		return object;
	},
});

/**
 * Generates a title for a session based on the user's prompt.
 * Returns "Untitled Session" on failure.
 */
export async function generateSessionTitleAction(
	prompt: string,
): Promise<string> {
	try {
		const modelId = await getSelectedModelId("light");
		const { text } = await generateText({
			model: myProvider.languageModel(modelId),
			system:
				"Generate a concise title (3-6 words) for this task. Output ONLY the title.",
			prompt: prompt,
		});
		return text.replace(/^["']|["']$/g, "").trim();
	} catch {
		return "Untitled Session";
	}
}

/**
 * Discovers potential features or improvements by analyzing the codebase context.
 */
export const discoverFeaturesAction = createAdminAction({
	input: discoverFeaturesSchema,
	handler: async () => {
		const modelId = await getSelectedModelId("large");
		const context = await getProjectContext();

		const { object } = await generateObject({
			model: myProvider.languageModel(modelId),
			schema: z.object({
				features: z.array(
					z.object({
						title: z.string(),
						description: z.string(),
						reasoning: z.string(),
						impact: z.enum(["High", "Medium", "Low"]),
						type: z.enum(["Feature", "Refactor", "Test", "Docs"]),
					}),
				),
			}),
			system: `You are a visionary Product Manager and Lead Architect for this project.
			Analyze the provided project documentation and standards.
			Identify 3-5 high-value features, architectural improvements, or technical debt items that should be addressed next.
			Focus on:
			1. Gaps in the current architecture.
			2. Enhancing the "Writer" or "Brain" modules.
			3. Improving developer experience or stability.

			Context:
			${context}`,
			prompt: "Propose a roadmap of strategic improvements.",
		});

		return object.features;
	},
});

/**
 * Plans a specific feature in detail, breaking it down into GitHub Issues.
 */
export const planFeatureAction = createAdminAction({
	input: planFeatureSchema,
	handler: async ({ input }) => {
		const modelId = await getSelectedModelId("large");
		const context = await getProjectContext();

		const { object } = await generateObject({
			model: myProvider.languageModel(modelId),
			schema: z.object({
				parentIssue: z.object({
					title: z.string(),
					body: z.string(),
					labels: z.array(z.string()),
				}),
				childIssues: z.array(
					z.object({
						title: z.string(),
						body: z.string(),
						labels: z.array(z.string()),
					}),
				),
			}),
			system: `You are a Software Architect.
			Your goal is to plan the implementation of a new feature: "${input.title}".

			1. Create a "Parent Issue" (Epic) describing the high-level goal and scope.
			2. Break it down into smaller, implementable "Child Issues" (Tasks).
			3. Ensure the plan aligns with the project's architecture and coding standards.

			Context:
			${context}
			${input.description ? `\nUser Description:\n${input.description}` : ""}`,
			prompt: `Plan the feature: "${input.title}"`,
		});

		return object;
	},
});
