"use server";

import { generateObject, generateText } from "ai";
import { z } from "zod";
import { createAdminAction } from "@/lib/action-middleware";
import { getSelectedModelId } from "@/lib/ai/models";
import { myProvider } from "@/lib/ai/providers";

// ============================================================================
// Validation Schemas
// ============================================================================

const enhancePromptSchema = z.object({
	draft: z.string().min(5, "Prompt is too short to enhance"),
});

const reviewPlanSchema = z.object({
	plan: z.object({
		steps: z.array(
			z.object({
				description: z.string(),
				state: z.string().optional(),
			}),
		),
	}),
});

const _generateTitleSchema = z.object({
	prompt: z.string().min(1, "Prompt is required"),
});

// ============================================================================
// Actions
// ============================================================================

/**
 * Enhance a user's draft prompt into a more detailed, actionable instruction
 */
export const enhanceJulesPromptAction = createAdminAction({
	input: enhancePromptSchema,
	handler: async ({ input }) => {
		const modelId = await getSelectedModelId("middle");

		const { text } = await generateText({
			model: myProvider.languageModel(modelId),
			system: `You are an expert technical lead. Your goal is to refine user tasks into precise, actionable instructions for an autonomous AI developer agent.
			Ensure the prompt covers:
			1. Specific goals
			2. Edge cases
			3. Testing requirements
			4. Context/Constraints

			Output ONLY the refined prompt text. Do not add conversational filler.`,
			prompt: `Refine this task: "${input.draft}"`,
		});

		return text;
	},
});

/**
 * Review a Jules plan using AI for security and logic analysis
 */
export const reviewJulesPlanAction = createAdminAction({
	input: reviewPlanSchema,
	handler: async ({ input }) => {
		const modelId = await getSelectedModelId("large");

		const { object } = await generateObject({
			model: myProvider.languageModel(modelId),
			schema: z.object({
				riskLevel: z.enum(["LOW", "MEDIUM", "HIGH", "CRITICAL"]),
				analysis: z.string(),
				recommendations: z.array(z.string()),
			}),
			system: `You are a Senior Staff Engineer reviewing a plan generated by an AI agent.
			Analyze the steps for safety, logic gaps, and potential side effects.
			Be critical but constructive.`,
			prompt: `Review this plan:\n${JSON.stringify(input.plan.steps, null, 2)}`,
		});

		return object;
	},
});

/**
 * Generates a title for a session based on the user's prompt.
 * Returns "Untitled Session" on failure.
 */
export async function generateSessionTitleAction(
	prompt: string,
): Promise<string> {
	try {
		const modelId = await getSelectedModelId("light");
		const { text } = await generateText({
			model: myProvider.languageModel(modelId),
			system:
				"Generate a concise title (3-6 words) for this task. Output ONLY the title.",
			prompt: prompt,
		});
		return text.replace(/^["']|["']$/g, "").trim();
	} catch {
		return "Untitled Session";
	}
}
