name: Deploy Storybook

on:
  push:
    branches: ["main"]
    paths:
      - "src/**/*"
      - ".storybook/**/*"
      - "package.json"
      - "pnpm-lock.yaml"
      - "!src/app/api/**/*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: "--max-old-space-size=6144"

jobs:
  storybook:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: ./.github/actions/setup
      - run: pnpm build-storybook
      - run: touch storybook-static/.nojekyll
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4
        with:
          branch: gh-pages
          folder: storybook-static
          clean: true
          clean-exclude: |
            supervisor/
          token: ${{ secrets.GITHUB_TOKEN }}
