name: Deploy Storybook

on:
  push:
    branches: ["main"]
    paths:
      - "src/**/*"
      - ".storybook/**/*"
      - "package.json"
      - "pnpm-lock.yaml"
      - "!src/app/api/**/*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: "--max-old-space-size=6144"

jobs:
  storybook:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: ./.github/actions/setup
      - run: pnpm build-storybook
      - run: touch storybook-static/.nojekyll
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@9d877eea73427180ae43cf98e8914934fe157a1a # v4
        with:
          branch: gh-pages
          folder: storybook-static
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
